version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: braintree
    versions:
    - 3.2.0
    - 3.3.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: oj
    versions:
    - 3.11.2
    - 3.11.3
  - dependency-name: cloudinary
    versions:
    - 1.18.1
    - 1.19.0
  - dependency-name: rollbar
    versions:
    - 3.1.1
