---
development:
  cloud_name: dg7gyrbqf
  api_key: ENV["CLOUDINARY_API"]
  api_secret: ENV["CLOUDINARY_SECRET"]
  enhance_image_tag: true
  static_image_support: true
production:
  cloud_name: dg7gyrbqf
  api_key: ENV["CLOUDINARY_API"]
  api_secret: ENV["CLOUDINARY_SECRET"]
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dg7gyrbqf
  api_key: ENV["CLOUDINARY_API"]
  api_secret: ENV["CLOUDINARY_SECRET"]
  enhance_image_tag: true
  static_image_support: true
staging:
  cloud_name: dg7gyrbqf
  api_key: ENV["CLOUDINARY_API"]
  api_secret: ENV["CLOUDINARY_SECRET"]
  enhance_image_tag: true
  static_image_support: true
