---
development:
  cloud_name: dg7gyrbqf
  api_key: '173961342875833'
  api_secret: ZRQwr-T2SF1ZzfwSbwBOQCTcMqE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dg7gyrbqf
  api_key: '173961342875833'
  api_secret: ZRQwr-T2SF1ZzfwSbwBOQCTcMqE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dg7gyrbqf
  api_key: '173961342875833'
  api_secret: ZRQwr-T2SF1ZzfwSbwBOQCTcMqE
  enhance_image_tag: true
  static_image_support: false
