default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  

development:
  <<: *default
  database: lumumba_development

test:
  <<: *default
  database: lumumba_test

production:
  <<: *default
  database: lumumba_production

staging:
  <<: *default
  database: lumumba_staging
